# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{actic}
  s.version = "0.0.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Steve Caney"]
  s.date = %q{2010-08-07}
  s.description = %q{}
  s.email = %q{steve@apptrix.net}
  s.extra_rdoc_files = [
    "README"
  ]
  s.files = [
    "Gemfile",
     "VERSION",
     "config/locales/en.yml",
     "lib/generators/actic/actic_generator.rb",
     "lib/generators/actic/install_generator.rb",
     "lib/generators/actic/orm_helpers.rb",
     "lib/generators/active_record/actic_generator.rb",
     "lib/generators/active_record/templates/actic.rb",
     "lib/generators/active_record/templates/migration.rb"
  ]
  s.homepage = %q{http://github.com/apptrix/actic}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{iCalendar wrapper for Active Record objects}
  s.test_files = [
    "test/actic_test.rb",
     "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

